# Generated by Django 4.1.2 on 2022-11-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
    ]
